"""inclusaão de campo(reposndido)

Revision ID: 3d8c919f10c9
Revises: 379671c2294f
Create Date: 2025-08-09 03:25:57.502826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8c919f10c9'
down_revision = '379671c2294f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repondido', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('repondido')

    # ### end Alembic commands ###
